apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels: 
      bb: web
  template: 
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: prikale/todo-app-prod
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  selector: 
    bb: web
  type: LoadBalancer
  ports:
    - protocol: TCP 
      port: 8000
      targetPort: 8000
      nodePort: 31100
